ImageManager.MVC/Controllers/NotificationController.cs
using ImageManager.MVC.Constants;
using ImageManager.MVC.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace ImageManager.MVC.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class NotificationController : Controller
    {
        private readonly ILogger<NotificationController> _logger;
        private readonly INotificationService _notificationService;

        public NotificationController(ILogger<NotificationController> logger,
            INotificationService notificationService)
        {
            _logger = logger;
            _notificationService = notificationService;
        }


        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            _logger.LogInformation("GetAll action.");
            return View(await _notificationService.GetNotificationsAsync(User.Identity.Name));
        }

        [HttpGet]
        public async Task<IActionResult> ShowImage(int notificationId)
        {
            _logger.LogInformation($"ShowImage action with notificationId = {notificationId}.");
            await _notificationService.MarkNotificationAsReadAsync(notificationId);
            return View(await _notificationService.GetImagePathAsync(notificationId));
        }
    }
}

ImageManager.MVC/Controllers/ProfileController.cs
using ImageManager.MVC.Constants;
using ImageManager.MVC.Filters;
using ImageManager.MVC.Services.Interfaces;
using ImageManager.MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace ImageManager.MVC.Controllers
{
    [BlockedFilter]
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly ILogger<ProfileController> _logger;
        private readonly IProfileService _profileService;

        public ProfileController(ILogger<ProfileController> logger,
            IProfileService profileService)
        {
            _logger = logger;
            _profileService = profileService;
        }

        [HttpGet]
        public async Task<IActionResult> Show()
        {
            _logger.LogInformation("Show action of ProfileController.");
            return View(await _profileService.GetUserInfoAsync(User.Identity.Name));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            _logger.LogInformation($"Edit get action of ProfileController with userId = {userId}.");
            return View(await _profileService.GetUserForEditAsync(userId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserInfoViewModel model)
        {
            _logger.LogInformation($"Edit post action of ProfileController with UserInfoViewModel = {JsonConvert.SerializeObject(model)}.");
            await _profileService.EditUserAsync(model);
            return RedirectToAction(RedirectPath.ShowAction , RedirectPath.ProfileController);
        }
    }
}

ImageManager.MVC/Controllers/UserController.cs
using ImageManager.MVC.Constants;
using ImageManager.MVC.Filters;
using ImageManager.MVC.Services.Interfaces;
using ImageManager.MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace ImageManager.MVC.Controllers
{
    [BlockedFilter]
    [Authorize(Roles = UserRoles.Admin)]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IStringLocalizer<UserController> _localizer;
        private readonly IUserService _userService;
        private readonly IAccountService _accountService;
        private readonly ISubscriptionService _subscriptionService;
        private readonly IImageService _imageService;

        public UserController(ILogger<UserController> logger,
            IStringLocalizer<UserController> localizer,
            IUserService userService,
            ISubscriptionService subscriptionService,
            IAccountService accountService,
            IImageService imageService)
        {
            _logger = logger;
            _localizer = localizer;
            _userService = userService;
            _accountService = accountService;
            _subscriptionService = subscriptionService;
            _imageService = imageService;
        }

        [HttpGet]
        public async Task<IActionResult> ShowAll()
        {
            _logger.LogInformation("ShowAll action of UserController.");
            return View(await _userService.GetAllUsersWithRolesAsync(User.Identity.Name));
        }

        [HttpGet]
        public async Task<IActionResult> ShowImage(string userId)
        {
            _logger.LogInformation($"ShowImage action of UserController with userId = {userId}.");
            return View(await _imageService.GetImagesByUserIdAsync(userId));
        }

        [HttpGet]
        public async Task<IActionResult> Activate(string userId)
        {
            _logger.LogInformation("Activate action of UserController.");
            await _userService.ActivateAsync(userId);
            return RedirectToAction(RedirectPath.ShowAllAction, RedirectPath.UserController);
        }

        [HttpGet]
        public async Task<IActionResult> Deactivate(string userId)
        {
            _logger.LogInformation("Deactivate action of UserController.");
            await _userService.DeactivateAsync(userId);
            return RedirectToAction(RedirectPath.ShowAllAction, RedirectPath.UserController);
        }

        [HttpGet]
        public IActionResult Create()
        {
            _logger.LogInformation("Create get action of UserController.");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            _logger.LogInformation($"Create post action of UserController with model = {JsonConvert.SerializeObject(model)}.");
            if (!ModelState.IsValid || model == null)
            {
                _logger.LogDebug("Create action, model is not valid.");
                return View(model);
            }

            if (model.IsAdmin == false && model.IsUser == false)
            {
                ModelState.AddModelError(string.Empty, _localizer[ModelErrorMessages.RoleNotSelected]);
                _logger.LogDebug("Create action, no one roles selected.");
                return View(model);
            }

            if (!await _accountService.IsEmailUniqueAsync(model.Email))
            {
                ModelState.AddModelError(ModelErrorMessages.EmailField, _localizer[ModelErrorMessages.EmailIsNotUnique]);
                _logger.LogDebug("Create action, email is not unique.");
                return View(model);
            }

            var user = await _userService.CreateUserAsync(model);
            if (user != null)
            {
                _logger.LogDebug("Create action, user created.");
                return RedirectToAction(RedirectPath.ShowAllAction, RedirectPath.UserController);
            }
            else
            {
                ModelState.AddModelError(string.Empty, _localizer[ModelErrorMessages.SomethingIsGoingWrong]);
                _logger.LogDebug("Create action, something was wrong while create user.");
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            _logger.LogInformation($"Edit get action of UserController with userId = {userId}.");
            return View(await _userService.GetEditUserViewModel(userId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            _logger.LogInformation($"Edit post action of UserController with model = {JsonConvert.SerializeObject(model)}.");
            if (!ModelState.IsValid || model == null)
            {
                _logger.LogDebug("Edit action, model is not valid.");
                return View(model);
            }

            if (model.IsAdmin == false && model.IsUser == false)
            {
                ModelState.AddModelError(string.Empty, _localizer[ModelErrorMessages.RoleNotSelected]);
                _logger.LogDebug("Edit action, no one roles selected.");
                return View(model);
            }

            var modelBefore = await _userService.GetEditUserViewModel(model.Id);
            if (modelBefore.Email != model.Email && await _accountService.IsEmailUniqueAsync(model.Email) == false)
            {
                ModelState.AddModelError(ModelErrorMessages.EmailField, _localizer[ModelErrorMessages.EmailIsNotUnique]);
                _logger.LogDebug("Edit action, email is not unique.");
                return View(model);
            }
            else
            {
                await _userService.EditUserAsync(model);
                _logger.LogDebug("Edit action, user edited.");
                return RedirectToAction(RedirectPath.ShowAllAction, RedirectPath.UserController);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string userId)
        {
            _logger.LogInformation($"Delete action of UserController with userId = {userId}.");
            await _userService.DeleteAsync(userId);
            return RedirectToAction(RedirectPath.ShowAllAction, RedirectPath.UserController);
        }

        [HttpGet]
        public async Task<IActionResult> Subscribe(string userId)
        {
            _logger.LogInformation($"Subscribe action of UserController with userId = {userId}.");
            await _subscriptionService.AddSubscriptionAsync(User.Identity.Name, userId);
            return RedirectToAction(RedirectPath.ShowAllAction, RedirectPath.UserController);
        }

        [HttpGet]
        public async Task<IActionResult> Unsubscribe(string userId)
        {
            _logger.LogInformation($"Unsubscribe action of UserController with userId = {userId}.");
            await _subscriptionService.DeactivateSubscriptionAsync(User.Identity.Name, userId);
            return RedirectToAction(RedirectPath.ShowAllAction, RedirectPath.UserController);
        }
    }
}

ImageManager.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/MyStyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/MyStyle.css" />
</head>
<body>
    <header>
        <div class="d-flex justify-content-md-between p-md-3 text-white" style="background: #57233e">
            <div class="d-sm-inline-flex ml-md-5">
                @if (User.IsInRole(ImageManager.MVC.Constants.UserRoles.User))
                {
                    <a asp-action="Index" asp-controller="Home" class="text-white m-2" id="homeLink">@Localizer["BasePage"]</a>
                    <a asp-action="History" asp-controller="Home" class="text-white m-2" id="historyLink">@Localizer["HistoryPage"]</a>
                }
                @if (User.IsInRole(ImageManager.MVC.Constants.UserRoles.Admin))
                {
                    <a asp-action="ShowAll" asp-controller="User" class="text-white m-2" id="usersLink">@Localizer["UsersPage"]</a>
                    <a asp-action="GetAll" asp-controller="Notification" class="text-white m-2" id="notificationLink">@Localizer["NotificationPage"]</a>
                }
            </div>

            <div class="d-sm-inline-flex pr-md-5">
                @await Html.PartialAsync("_SelectLanguagePartial")
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-action="Show" asp-controller="Profile" class="text-white m-2" id="profileLink">@User.Identity.Name</a>
                    <a asp-action="Logout" asp-controller="Account" class="text-white m-2" id="logoutLink">@Localizer["LogoutAction"]</a>
                }
                else
                {
                    <a asp-action="Login" asp-controller="Account" class="text-white m-2" id="loginLink">@Localizer["LoginPage"]</a>
                    <a asp-action="Register" asp-controller="Account" class="text-white m-2" id="registerLink">@Localizer["RegisterPage"]</a>
                }
            </div>
        </div>
    </header>
    <div class="">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - @Localizer["SiteTextFooter"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Policy"].</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/MyScripts.js"></script>
    <script src="~/js/Localization.js"></script>
    <script src="~/js/.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>                     
            

ImageManager.MVC/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage"
      asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString"
      method="post" class="form-horizontal m-2 ">
    <select name="culture" 
            class="select-lang rounded"
            onchange="this.form.submit();"
            asp-for="@requestCulture.RequestCulture.UICulture.Name"
            asp-items="cultureItems">

    </select>
</form>